config/routes.rb
Rails.application.routes.draw do
  get 'info/index'
  
  resources :support_requests
  resources :areas
  devise_for :members, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :members

  get 'home/index'
  root :to => 'home#index'
  resources :comentarios
  
  resources :statistcs
  
  post 'importar' => 'risk_areas#csv_import'
  post 'import_area' => 'areas#csv_import'
  post 'import_request' => 'support_requests#csv_import'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/support_request.rb
class SupportRequest < ApplicationRecord
end

app/controllers/support_requests_controller.rb
class SupportRequestsController < ApplicationController
  before_action :set_support_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_member!

  # GET /support_requests
  # GET /support_requests.json
  def index
    @support_requests = SupportRequest.all
  end

  # GET /support_requests/1
  # GET /support_requests/1.json
  def show
    @calendario = SupportRequest.select('solicitacao_data')
  end

  # GET /support_requests/new
  def new
    @support_request = SupportRequest.new
  end
  
  #Importar dados do CSV
  def csv_import
    #n = 0
    CSV.foreach(params[:dump][:file].tempfile,:col_sep => ';', :encoding => 'ISO-8859-1') do |row|
      c = SupportRequest.new( :ano                        => row[0],
                              :mes                        => row[1],
                              :processo_numero            => row[2],
                              :solicitacao_data           => row[3],
                              :solicitacao_hora           => row[4],
                              :solicitacao_descricao      => row[5],
                              :solicitacao_regional       => row[6],
                              :solicitacao_bairro         => row[7],
                              :solicitacao_localidade     => row[8],
                              :solicitacao_endereco       => row[9],
                              :solicitacao_roteiro        => row[10],
                              :rpa_codigo                 => row[11],
                              :rpa_nome                   => row[12],
                              :solicitacao_microrregiao   => row[13],
                              :solicitacao_plantao        => row[14],
                              :solicitacao_origem_chamado => row[15],
                              :latitude                   => row[16],
                              :longitude                  => row[17],
                              :solicitacao_vitimas        => row[18],
                              :solicitacao_vitimas_fatais => row[19],
                              :processo_tipo              => row[20],
                              :processo_origem            => row[21],
                              :processo_localizacao       => row[22],
                              :processo_status            => row[23],
                              :processo_data_conclusao    => row[24])
      c.save
    end
#    redirect_to :action => "index" and return
  end

  # GET /support_requests/1/edit
  def edit
  end

  # POST /support_requests
  # POST /support_requests.json
  def create
    @support_request = SupportRequest.new(support_request_params)

    respond_to do |format|
      if @support_request.save
        format.html { redirect_to @support_request, notice: 'Support request was successfully created.' }
        format.json { render :show, status: :created, location: @support_request }
      else
        format.html { render :new }
        format.json { render json: @support_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /support_requests/1
  # PATCH/PUT /support_requests/1.json
  def update
    respond_to do |format|
      if @support_request.update(support_request_params)
        format.html { redirect_to @support_request, notice: 'Support request was successfully updated.' }
        format.json { render :show, status: :ok, location: @support_request }
      else
        format.html { render :edit }
        format.json { render json: @support_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /support_requests/1
  # DELETE /support_requests/1.json
  def destroy
    @support_request.destroy
    respond_to do |format|
      format.html { redirect_to support_requests_url, notice: 'Support request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support_request
      @support_request = SupportRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def support_request_params
      params.require(:support_request).permit(:ano, :mes, :processo_numero, :solicitacao_data, :solicitacao_hora, :solicitacao_descricao, :solicitacao_regional, :solicitacao_bairro, :solicitacao_localidade, :solicitacao_endereco, :solicitacao_roteiro, :rpa_codigo, :rpa_nome, :solicitacao_microrregiao, :solicitacao_plantao, :solicitacao_origem_chamado, :latitude, :longitude, :solicitacao_vitimas, :solicitacao_vitimas_fatais, :processo_tipo, :processo_origem, :processo_localizacao, :processo_status, :processo_data_conclusao)
    end
    
    def calendario
      
    end
end

app/helpers/support_requests_helper.rb
module SupportRequestsHelper
end

app/views/support_requests/_form.html.erb
<%= form_with(model: support_request, local: true) do |form| %>
  <% if support_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(support_request.errors.count, "error") %> prohibited this support_request from being saved:</h2>

      <ul>
      <% support_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano, id: :support_request_ano %>
  </div>

  <div class="field">
    <%= form.label :mes %>
    <%= form.text_field :mes, id: :support_request_mes %>
  </div>

  <div class="field">
    <%= form.label :processo_numero %>
    <%= form.text_field :processo_numero, id: :support_request_processo_numero %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_data %>
    <%= form.date_select :solicitacao_data, id: :support_request_solicitacao_data %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_hora %>
    <%= form.time_select :solicitacao_hora, id: :support_request_solicitacao_hora %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_descricao %>
    <%= form.text_field :solicitacao_descricao, id: :support_request_solicitacao_descricao %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_regional %>
    <%= form.text_field :solicitacao_regional, id: :support_request_solicitacao_regional %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_bairro %>
    <%= form.text_field :solicitacao_bairro, id: :support_request_solicitacao_bairro %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_localidade %>
    <%= form.text_field :solicitacao_localidade, id: :support_request_solicitacao_localidade %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_endereco %>
    <%= form.text_field :solicitacao_endereco, id: :support_request_solicitacao_endereco %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_roteiro %>
    <%= form.text_field :solicitacao_roteiro, id: :support_request_solicitacao_roteiro %>
  </div>

  <div class="field">
    <%= form.label :rpa_codigo %>
    <%= form.number_field :rpa_codigo, id: :support_request_rpa_codigo %>
  </div>

  <div class="field">
    <%= form.label :rpa_nome %>
    <%= form.text_field :rpa_nome, id: :support_request_rpa_nome %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_microrregiao %>
    <%= form.text_field :solicitacao_microrregiao, id: :support_request_solicitacao_microrregiao %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_plantao %>
    <%= form.text_field :solicitacao_plantao, id: :support_request_solicitacao_plantao %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_origem_chamado %>
    <%= form.text_field :solicitacao_origem_chamado, id: :support_request_solicitacao_origem_chamado %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :support_request_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :support_request_longitude %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_vitimas %>
    <%= form.text_field :solicitacao_vitimas, id: :support_request_solicitacao_vitimas %>
  </div>

  <div class="field">
    <%= form.label :solicitacao_vitimas_fatais %>
    <%= form.text_field :solicitacao_vitimas_fatais, id: :support_request_solicitacao_vitimas_fatais %>
  </div>

  <div class="field">
    <%= form.label :processo_tipo %>
    <%= form.text_field :processo_tipo, id: :support_request_processo_tipo %>
  </div>

  <div class="field">
    <%= form.label :processo_origem %>
    <%= form.text_field :processo_origem, id: :support_request_processo_origem %>
  </div>

  <div class="field">
    <%= form.label :processo_localizacao %>
    <%= form.text_field :processo_localizacao, id: :support_request_processo_localizacao %>
  </div>

  <div class="field">
    <%= form.label :processo_status %>
    <%= form.text_field :processo_status, id: :support_request_processo_status %>
  </div>

  <div class="field">
    <%= form.label :processo_data_conclusao %>
    <%= form.datetime_select :processo_data_conclusao, id: :support_request_processo_data_conclusao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/support_requests/csv_import.html.erb
Cadastro realizado com sucesso.

<%= link_to 'Back', support_requests_path %>

app/views/support_requests/edit.html.erb
<h1>Editing Support Request</h1>

<%= render 'form', support_request: @support_request %>

<%= link_to 'Show', @support_request %> |
<%= link_to 'Back', support_requests_path %>

app/views/support_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Support Requests</h1>

<table>
  <thead>
    <tr>
      <th>Ano</th>
      <th>Mes</th>
      <th>Processo numero</th>
      <th>Solicitacao data</th>
      <th>Solicitacao hora</th>
      <th>Solicitacao descricao</th>
      <th>Solicitacao regional</th>
      <th>Solicitacao bairro</th>
      <th>Solicitacao localidade</th>
      <th>Solicitacao endereco</th>
      <th>Solicitacao roteiro</th>
      <th>Rpa codigo</th>
      <th>Rpa nome</th>
      <th>Solicitacao microrregiao</th>
      <th>Solicitacao plantao</th>
      <th>Solicitacao origem chamado</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Solicitacao vitimas</th>
      <th>Solicitacao vitimas fatais</th>
      <th>Processo tipo</th>
      <th>Processo origem</th>
      <th>Processo localizacao</th>
      <th>Processo status</th>
      <th>Processo data conclusao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @support_requests.each do |support_request| %>
      <tr>
        <td><%= support_request.ano %></td>
        <td><%= support_request.mes %></td>
        <td><%= support_request.processo_numero %></td>
        <td><%= support_request.solicitacao_data %></td>
        <td><%= support_request.solicitacao_hora %></td>
        <td><%= support_request.solicitacao_descricao %></td>
        <td><%= support_request.solicitacao_regional %></td>
        <td><%= support_request.solicitacao_bairro %></td>
        <td><%= support_request.solicitacao_localidade %></td>
        <td><%= support_request.solicitacao_endereco %></td>
        <td><%= support_request.solicitacao_roteiro %></td>
        <td><%= support_request.rpa_codigo %></td>
        <td><%= support_request.rpa_nome %></td>
        <td><%= support_request.solicitacao_microrregiao %></td>
        <td><%= support_request.solicitacao_plantao %></td>
        <td><%= support_request.solicitacao_origem_chamado %></td>
        <td><%= support_request.latitude %></td>
        <td><%= support_request.longitude %></td>
        <td><%= support_request.solicitacao_vitimas %></td>
        <td><%= support_request.solicitacao_vitimas_fatais %></td>
        <td><%= support_request.processo_tipo %></td>
        <td><%= support_request.processo_origem %></td>
        <td><%= support_request.processo_localizacao %></td>
        <td><%= support_request.processo_status %></td>
        <td><%= support_request.processo_data_conclusao %></td>
        <td><%= link_to 'Show', support_request %></td>
        <td><%= link_to 'Edit', edit_support_request_path(support_request) %></td>
        <td><%= link_to 'Destroy', support_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2> Import </h2>
<%= form_for :dump, :url => import_request_path, :html => { :multipart => true} do |f| -%>
  <table>
    <tr>
      <td>
        <label for = "dump_file">
          Selecione um arquivo CSV:
        </label>
      </td>
      <td>
        <%= f.file_field :file -%>
      </td>
    </tr>
    <tr>
      <td colspan='2'>
        <%= submit_tag 'Import' -%>
      </td>
    </tr>
  </table>
<% end -%>

<br>

<%= link_to 'New Support Request', new_support_request_path %>
<p>Voltar ao <%= link_to "Menu Principal", root_path %></p>

app/views/support_requests/new.html.erb
<h1>New Support Request</h1>

<%= render 'form', support_request: @support_request %>

<%= link_to 'Back', support_requests_path %>

app/views/support_requests/show.html.erb
<p>teste   <%=@calendario.to_s %></p>
</p>