config/routes.rb
Rails.application.routes.draw do
  get 'info/index'
  
  resources :support_requests
  resources :areas
  devise_for :members, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :members

  get 'home/index'
  root :to => 'home#index'
  resources :comentarios
  
  resources :statistcs
  
  post 'importar' => 'risk_areas#csv_import'
  post 'import_area' => 'areas#csv_import'
  post 'import_request' => 'support_requests#csv_import'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
    after_save :write_json

    def write_json
        dados_json = []
        Area.all.each do |area|
            dado_json = {
            "latitude" => area.latitude,
            "longitude" => area.longitude
            } 
        dados_json << dado_json
    
        end
        File.open("public/dados.json","w") do |f|
          f.write(dados_json.to_json)
        end
    end

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_member!

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
     @area = Area.new
  end
  
  #Importar dados do CSV
  def csv_import
    #n = 0
    CSV.foreach(params[:dump][:file].tempfile,:col_sep => ';', :encoding => 'ISO-8859-1:UTF-8') do |row|
      c = Area.new(:regional => row[0],
                   :endereco => row[1],
                   :bairro => row[2],
                   :localidade => row[3],
                   :descricao => row[4],
                   :latitude => row[5],
                   :longitude => row[6])
      c.save
    end
    #redirect_to :action => "index" and return
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:regional, :endereco, :bairro, :localidade, :descricao, :latitude, :longitude)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <title>Encostaki</title>
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
    
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	  <%= stylesheet_link_tag "css/bootstrap" %>
    <link href="css/novaarea.scss" type="text/css"  rel="stylesheet">
</head>



<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-4 col-sm-4">
				<div id="esquerda-l">
				</div>
			</div>
			<div class="col-md-4 text-center col-sm-4 text-center">
        <div id="center">
          <h1>Nova Área</h1>
            <%= image_tag('logopinfinal.png', id:'logopin') %>
          <%= form_with(model: area, local: true) do |form| %>
            <% if area.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>
          
                <ul>
                <% area.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
          
            <div class="field">
              <p>Regional</p>
              <%= form.text_field :regional, id: :area_regional %>
            </div>
          
            <div class="field">
              <p>Endereço</p>
              <%= form.text_field :endereco, id: :area_endereco %>
            </div>
          
            <div class="field">
              <p>Bairro</p>
              <%= form.text_field :bairro, id: :area_bairro %>
            </div>
          
            <div class="field">
              <p>Localidade</p>
              <%= form.text_field :localidade, id: :area_localidade %>
            </div>
          
            <div class="field">
              <p>Descrição</p>
              <%= form.text_field :descricao, id: :area_descricao %>
            </div>
          
            <div class="field">
              <p>Latitude</p>
              <%= form.text_field :latitude, id: :area_latitude %>
            </div>
          
            <div class="field">
              <p>Longitude</p>
              <%= form.text_field :longitude, id: :area_longitude %>
            </div>
          
            <div class="actions">
            <button class="btn btn-warning"><% form.submit %>Criar Área</button>
            </div>
    </body>
          <% end %>

<p>Voltar ao <%= link_to 'Menu Principal', root_path %></p>

app/views/areas/csv_import.html.erb
Cadastro realizado com sucesso.

<%= link_to 'Back', areas_path %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<% if current_member.admin? %>
  <p id="notice"><%= notice %></p>
  
  <h1>Areas</h1>
  
  <table>
    <thead>
      <tr>
        <th>Regional</th>
        <th>Endereco</th>
        <th>Bairro</th>
        <th>Localidade</th>
        <th>Descricao</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @areas.each do |area| %>
        <tr>
          <td><%= area.regional %></td>
          <td><%= area.endereco %></td>
          <td><%= area.bairro %></td>
          <td><%= area.localidade %></td>
          <td><%= area.descricao %></td>
          <td><%= area.latitude %></td>
          <td><%= area.longitude %></td>
          <td><%= link_to 'Show', area %></td>
          <td><%= link_to 'Edit', edit_area_path(area) %></td>
          <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= pie_chart Area.group(:localidade).count %>
  
  <h2> Import </h2>
  <%= form_for :dump, :url => import_area_path, :html => { :multipart => true} do |f| -%>
    <table>
      <tr>
        <td>
          <label for = "dump_file">
            Selecione um arquivo CSV:
          </label>
        </td>
        <td>
          <%= f.file_field :file -%>
        </td>
      </tr>
      <tr>
        <td colspan='2'>
          <%= submit_tag 'Import' -%>
        </td>
      </tr>
    </table>
  <% end -%>
  
  <br>
  
  <%= link_to 'New Area', new_area_path %>
  <p>Voltar ao <%= link_to "Menu Principal", root_path %></p>
<%else %>
  <p>VOCÊ NÃO TEM PERMISSÃO PARA ISSO, APENAS UM ADMINISTRADOR TEM ACESSO!</p>
<%end%>

app/views/areas/new.html.erb
<% if current_member.admin? %>
    
    
    <%= render 'form', area: @area %>
    
    <%= link_to 'Back', areas_path %>
<%else %>
  <p>VOCÊ NÃO TEM PERMISSÃO PARA ISSO, APENAS UM ADMINISTRADOR TEM ACESSO!</p>
<%end%>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Regional:</strong>
  <%= @area.regional %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @area.endereco %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @area.bairro %>
</p>

<p>
  <strong>Localidade:</strong>
  <%= @area.localidade %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @area.descricao %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @area.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @area.longitude %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>